name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build for all platforms
        run: |
          mkdir -p dist
          VERSION=${{ github.event.inputs.version }}

          # Linux builds
          GOOS=linux GOARCH=amd64 go build -o dist/czgo .
          tar -czvf dist/czgo-${VERSION}-linux-amd64.tar.gz -C dist czgo

          GOOS=linux GOARCH=arm64 go build -o dist/czgo .
          tar -czvf dist/czgo-${VERSION}-linux-arm64.tar.gz -C dist czgo

          # macOS builds
          GOOS=darwin GOARCH=amd64 go build -o dist/czgo .
          tar -czvf dist/czgo-${VERSION}-darwin-amd64.tar.gz -C dist czgo

          GOOS=darwin GOARCH=arm64 go build -o dist/czgo .
          tar -czvf dist/czgo-${VERSION}-darwin-arm64.tar.gz -C dist czgo

          # Windows builds
          GOOS=windows GOARCH=amd64 go build -o dist/czgo.exe .
          cd dist && zip czgo-${VERSION}-windows-amd64.zip czgo.exe && cd ..

          GOOS=windows GOARCH=arm64 go build -o dist/czgo.exe .
          cd dist && zip czgo-${VERSION}-windows-arm64.zip czgo.exe && cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/czgo-${{ github.event.inputs.version }}-linux-amd64.tar.gz
            dist/czgo-${{ github.event.inputs.version }}-linux-arm64.tar.gz
            dist/czgo-${{ github.event.inputs.version }}-darwin-amd64.tar.gz
            dist/czgo-${{ github.event.inputs.version }}-darwin-arm64.tar.gz
            dist/czgo-${{ github.event.inputs.version }}-windows-amd64.zip
            dist/czgo-${{ github.event.inputs.version }}-windows-arm64.zip
          tag_name: ${{ github.event.inputs.version }}
          make_latest: true
          token: ${{ secrets.hehe }}
