name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for all platforms
        run: |
          mkdir -p dist

          # Linux builds
          GOOS=linux GOARCH=amd64 go build -o dist/czgo-${{ github.event.inputs.version }}-linux-amd64 .
          tar -czvf dist/czgo-${{ github.event.inputs.version }}-linux-amd64.tar.gz -C dist czgo-${{ github.event.inputs.version }}-linux-amd64

          GOOS=linux GOARCH=arm64 go build -o dist/czgo-${{ github.event.inputs.version }}-linux-arm64 .
          tar -czvf dist/czgo-${{ github.event.inputs.version }}-linux-arm64.tar.gz -C dist czgo-${{ github.event.inputs.version }}-linux-arm64

          # macOS builds
          GOOS=darwin GOARCH=amd64 go build -o dist/czgo-${{ github.event.inputs.version }}-darwin-amd64 .
          tar -czvf dist/czgo-${{ github.event.inputs.version }}-darwin-amd64.tar.gz -C dist czgo-${{ github.event.inputs.version }}-darwin-amd64

          GOOS=darwin GOARCH=arm64 go build -o dist/czgo-${{ github.event.inputs.version }}-darwin-arm64 .
          tar -czvf dist/czgo-${{ github.event.inputs.version }}-darwin-arm64.tar.gz -C dist czgo-${{ github.event.inputs.version }}-darwin-arm64

          # Windows builds
          GOOS=windows GOARCH=amd64 go build -o dist/czgo-${{ github.event.inputs.version }}-windows-amd64.exe .
          cd dist && zip czgo-${{ github.event.inputs.version }}-windows-amd64.zip czgo-${{ github.event.inputs.version }}-windows-amd64.exe && cd ..

          GOOS=windows GOARCH=arm64 go build -o dist/czgo-${{ github.event.inputs.version }}-windows-arm64.exe .
          cd dist && zip czgo-${{ github.event.inputs.version }}-windows-arm64.zip czgo-${{ github.event.inputs.version }}-windows-arm64.exe && cd ..

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Upload Linux AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/czgo-${{ github.event.inputs.version }}-linux-amd64.tar.gz
          asset_name: czgo-${{ github.event.inputs.version }}-linux-amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux ARM64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/czgo-${{ github.event.inputs.version }}-linux-arm64.tar.gz
          asset_name: czgo-${{ github.event.inputs.version }}-linux-arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/czgo-${{ github.event.inputs.version }}-darwin-amd64.tar.gz
          asset_name: czgo-${{ github.event.inputs.version }}-darwin-amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS ARM64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/czgo-${{ github.event.inputs.version }}-darwin-arm64.tar.gz
          asset_name: czgo-${{ github.event.inputs.version }}-darwin-arm64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/czgo-${{ github.event.inputs.version }}-windows-amd64.zip
          asset_name: czgo-${{ github.event.inputs.version }}-windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload Windows ARM64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/czgo-${{ github.event.inputs.version }}-windows-arm64.zip
          asset_name: czgo-${{ github.event.inputs.version }}-windows-arm64.zip
          asset_content_type: application/zip
